server:
  port: 8080

logging:
  level:
    org.springframework: DEBUG

# 언어 변경 빈등록
spring:
  messages:
    basename: message
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    user:
      name: username
      password: password

management:
  endpoints:
    web:
      exposure:
        include: "*"